# Generated by Django 5.1.5 on 2025-01-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_rename_url_event_detail_url_remove_event_tags_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="status",
        ),
        migrations.AddField(
            model_name="event",
            name="processing_state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("scraped", "Basic Info Scraped"),
                    ("enriched", "Fully Enriched"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["processing_state"], name="events_even_process_4d3367_idx"
            ),
        ),
    ]
