services:
  app:
    build: .
    container_name: app-container
    image: app-image
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?connect_timeout=1
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount entire project directory
      - /app/.venv  # Exclude virtual environment
      - /app/node_modules  # Exclude node_modules
    command: ["./start.sh"]
    # command: ["sh", "-c", "ls -la /app && cat /app/start.sh && ./start.sh"]
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    container_name: db-container
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1s
      timeout: 1s
      retries: 2

volumes:
  postgres_data:
